const API="http://localhost:5000/api";
let jobs=[], currentUser=JSON.parse(localStorage.getItem("jobsphereUser")||"null"), selectedJob=null, authMode="login";

const $=id=>document.getElementById(id);
function toast(msg){$("toast").textContent=msg;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2200)}
async function api(path,opts={}){const headers={"Content-Type":"application/json",...(opts.headers||{})};if(currentUser?.token)headers.Authorization=`Bearer ${currentUser.token}`;const r=await fetch(API+path,{...opts,headers});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.message||"Request failed");return data}

function updateAuthUI(){const logged=!!currentUser;$("authBtn").classList.toggle("hidden",logged);$("logoutBtn").classList.toggle("hidden",!logged);$("postJobBtn").classList.toggle("hidden",currentUser?.role!=="recruiter");$("dashboardPostBtn").classList.toggle("hidden",currentUser?.role!=="recruiter")}
function showView(view){$("landing").classList.toggle("hidden",view!=="home");$("jobsView").classList.toggle("hidden",view!=="jobs");$("dashboardView").classList.toggle("hidden",view!=="dashboard");if(view==="jobs")renderJobs();if(view==="dashboard")renderDashboard();window.scrollTo({top:0,behavior:"smooth"})}
async function loadJobs(){try{jobs=await api("/jobs")}catch(e){jobs=[];toast("Start the backend to load jobs")}renderJobs()}
function renderJobs(){const q=$("search").value.toLowerCase(),type=$("typeFilter").value,loc=$("locationFilter").value;const list=jobs.filter(j=>(!q||`${j.title} ${j.company} ${j.skills.join(" ")}`.toLowerCase().includes(q))&&(!type||j.type===type)&&(!loc||j.location===loc));$("jobs").innerHTML=list.length?list.map(j=>`<article class="job-card"><span class="eyebrow">${j.type}</span><h3>${esc(j.title)}</h3><div class="company">${esc(j.company)}</div><div class="job-meta"><span>${esc(j.location)}</span><span>•</span><span>${esc(j.salary||"Salary not listed")}</span></div><div class="tags">${j.skills.map(s=>`<span class="tag">${esc(s)}</span>`).join("")}</div><button class="primary apply" onclick="openApply('${j._id}')">${currentUser?.role==="recruiter"?"View role":"Apply now"}</button></article>`).join(""):`<div class="panel"><h3>No matching jobs</h3><p>Try another search or filter.</p></div>`}
function esc(s=""){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}

function openAuth(mode="login"){authMode=mode;$("authModal").classList.remove("hidden");$("authTitle").textContent=mode==="login"?"Sign in":"Create your account";$("loginTab").classList.toggle("active",mode==="login");$("registerTab").classList.toggle("active",mode==="register");document.querySelectorAll(".register-only").forEach(x=>x.classList.toggle("hidden",mode==="login"))}
function closeModal(id){$(id).classList.add("hidden")}
$("authBtn").onclick=()=>openAuth("login");$("heroAuth").onclick=()=>openAuth("register");$("loginTab").onclick=()=>openAuth("login");$("registerTab").onclick=()=>openAuth("register");
$("logoutBtn").onclick=()=>{currentUser=null;localStorage.removeItem("jobsphereUser");updateAuthUI();showView("home");toast("Logged out")}
$("authForm").onsubmit=async e=>{e.preventDefault();try{const path=authMode==="login"?"/auth/login":"/auth/register";const body={email:$("email").value,password:$("password").value};if(authMode==="register")Object.assign(body,{name:$("name").value,company:$("company").value,role:$("role").value});const data=await api(path,{method:"POST",body:JSON.stringify(body)});currentUser=data.user;localStorage.setItem("jobsphereUser",JSON.stringify(currentUser));updateAuthUI();closeModal("authModal");$("authForm").reset();toast("Welcome to JobSphere");showView("dashboard")}catch(e){toast(e.message)}}

$("jobForm").onsubmit=async e=>{e.preventDefault();try{await api("/jobs",{method:"POST",body:JSON.stringify({title:$("jobTitle").value,company:$("jobCompany").value,skills:$("jobSkills").value.split(",").map(x=>x.trim()).filter(Boolean),salary:$("jobSalary").value,type:$("jobType").value,location:$("jobLocation").value,description:$("jobDescription").value})});closeModal("jobModal");$("jobForm").reset();await loadJobs();toast("Job published");showView("jobs")}catch(e){toast(e.message)}}
$("postJobBtn").onclick=$("dashboardPostBtn").onclick=()=>{if(!currentUser)openAuth("login");else $("jobModal").classList.remove("hidden")}
async function openApply(id){selectedJob=jobs.find(j=>j._id===id);if(!currentUser){openAuth("login");return}if(currentUser.role==="recruiter"){toast("Recruiter accounts cannot apply");return}$("applyRole").textContent=`${selectedJob.title} at ${selectedJob.company}`;$("applyModal").classList.remove("hidden")}
$("applyForm").onsubmit=async e=>{e.preventDefault();try{await api("/applications",{method:"POST",body:JSON.stringify({jobId:selectedJob._id,coverNote:$("cover").value})});closeModal("applyModal");$("applyForm").reset();toast("Application submitted")}catch(e){toast(e.message)}}

async function renderDashboard(){if(!currentUser){$("dashboardContent").innerHTML=`<div class="panel"><h3>Sign in to continue</h3><p>Your dashboard contains applications or recruiter hiring activity.</p><button class="primary" onclick="openAuth('login')">Sign in</button></div>`;return}
$("dashboardTitle").textContent=currentUser.role==="recruiter"?`${currentUser.company||"Company"} workspace`:"Candidate dashboard";
try{const data=await api(currentUser.role==="recruiter"?"/dashboard/recruiter":"/dashboard/candidate");$("dashboardContent").innerHTML=currentUser.role==="recruiter"?recruiterDash(data):candidateDash(data)}catch(e){$("dashboardContent").innerHTML=`<div class="panel"><p>${esc(e.message)}</p></div>`}}
function recruiterDash(d){return `<div class="dashboard-grid"><div class="stat"><span>Total jobs</span><strong>${d.jobs.length}</strong></div><div class="stat"><span>Applications</span><strong>${d.applications.length}</strong></div><div class="stat"><span>Active roles</span><strong>${d.jobs.filter(j=>j.status==="open").length}</strong></div></div><div class="panel"><h3>Recent applications</h3><table class="table"><tr><th>Candidate</th><th>Role</th><th>Status</th></tr>${d.applications.map(a=>`<tr><td>${esc(a.candidateName)}</td><td>${esc(a.jobTitle)}</td><td><span class="status">${esc(a.status)}</span></td></tr>`).join("")||"<tr><td colspan=3>No applications yet</td></tr>"}</table></div>`}
function candidateDash(d){return `<div class="dashboard-grid"><div class="stat"><span>Applications</span><strong>${d.applications.length}</strong></div><div class="stat"><span>Submitted</span><strong>${d.applications.filter(a=>a.status==="submitted").length}</strong></div><div class="stat"><span>Profile</span><strong>Ready</strong></div></div><div class="panel"><h3>My applications</h3><table class="table"><tr><th>Role</th><th>Company</th><th>Status</th></tr>${d.applications.map(a=>`<tr><td>${esc(a.jobTitle)}</td><td>${esc(a.company)}</td><td><span class="status">${esc(a.status)}</span></td></tr>`).join("")||"<tr><td colspan=3>No applications yet</td></tr>"}</table></div>`}

document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>showView(b.dataset.view));
document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>closeModal(b.dataset.close));
["search","typeFilter","locationFilter"].forEach(id=>$(id).addEventListener("input",renderJobs));
loadJobs();updateAuthUI();
